version: '3.7'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
  caddy:
    image: caddy:2.6.4-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
